name: ci

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup bun
        uses: oven-sh/setup-bun@v2

      - name: install dependencies
        run: bun install

      - name: run biome checks
        run: bun run check

      - name: build
        run: bun run build

  # Additional job only for main and PRs to main
  publish-check:
    if: github.ref == 'refs/heads/main' || github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup bun
        uses: oven-sh/setup-bun@v2
        with:
          registry-url: "https://registry.npmjs.org"

      - name: install dependencies
        run: bun install

      - name: dry run publish
        run: bun publish --dry-run
        env:
          NPM_CONFIG_TOKEN: ${{secrets.NPM_TOKEN}}
